[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$schemaPath = Join-Path $repoRoot 'contracts\EventMonitorSnapshotContract.v1.json'
$nativePath = Join-Path $repoRoot 'BO2Monitor\Generated\EventMonitorSnapshotContract.g.h'
$managedPath = Join-Path $repoRoot 'Services\Generated\EventMonitorSnapshotContract.g.cs'
$newLine = "`r`n"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Get-RequiredString($value, [string]$name) {
    if ($value -isnot [string] -or [string]::IsNullOrWhiteSpace($value)) {
        throw "Schema value '$name' must be a non-empty string."
    }

    return $value
}

function Get-EscapedCppWideString([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

function Get-EscapedCSharpString([string]$value) {
    return $value.Replace('\', '\\').Replace('"', '\"')
}

function Get-GeneratedText([string[]]$lines) {
    return ($lines -join $newLine) + $newLine
}

function Test-GeneratedFile([string]$path, [string]$expected) {
    if (-not (Test-Path -LiteralPath $path)) {
        Write-Error "Generated file is missing: $path"
        return $false
    }

    $actual = [System.IO.File]::ReadAllText($path)
    if ($actual -ne $expected) {
        Write-Error "Generated file is stale: $path"
        return $false
    }

    return $true
}

$contract = Get-Content -LiteralPath $schemaPath -Raw | ConvertFrom-Json

if ($contract.schemaVersion -ne 1) {
    throw "Unsupported Event Monitor Snapshot Contract schemaVersion '$($contract.schemaVersion)'."
}

$magicHex = Get-RequiredString $contract.snapshot.magicHex 'snapshot.magicHex'
if ($magicHex -notmatch '^0x[0-9A-Fa-f]{8}$') {
    throw "Schema value 'snapshot.magicHex' must be an 8-digit hexadecimal value with 0x prefix."
}

$snapshotMagic = [Convert]::ToUInt32($magicHex.Substring(2), 16)
$snapshotVersion = [uint32]$contract.snapshot.version
$magicLiteral = ('0x{0:X8}u' -f $snapshotMagic)
$versionLiteral = ('{0}u' -f $snapshotVersion)
$sharedMemoryPrefix = Get-RequiredString $contract.objectNamePrefixes.sharedMemory 'objectNamePrefixes.sharedMemory'
$updateEventPrefix = Get-RequiredString $contract.objectNamePrefixes.updateEvent 'objectNamePrefixes.updateEvent'
$stopEventPrefix = Get-RequiredString $contract.objectNamePrefixes.stopEvent 'objectNamePrefixes.stopEvent'
$schemaRelativePath = 'contracts/EventMonitorSnapshotContract.v1.json'
$generatorRelativePath = 'tools/Generate-EventMonitorSnapshotContract.ps1'

$nativeContent = Get-GeneratedText @(
    '#pragma once',
    '',
    '// <auto-generated />',
    "// Generated by $generatorRelativePath from $schemaRelativePath.",
    '',
    '#include <cstdint>',
    '',
    'namespace BO2Monitor::Generated',
    '{',
    "    constexpr std::uint32_t SnapshotMagic = $magicLiteral;",
    "    constexpr std::uint32_t SnapshotVersion = $versionLiteral;",
    ('    constexpr wchar_t SharedMemoryNamePrefix[] = L"{0}";' -f (Get-EscapedCppWideString $sharedMemoryPrefix)),
    ('    constexpr wchar_t UpdateEventNamePrefix[] = L"{0}";' -f (Get-EscapedCppWideString $updateEventPrefix)),
    ('    constexpr wchar_t StopEventNamePrefix[] = L"{0}";' -f (Get-EscapedCppWideString $stopEventPrefix)),
    '}'
)

$managedContent = Get-GeneratedText @(
    '// <auto-generated />',
    "// Generated by $generatorRelativePath from $schemaRelativePath.",
    '',
    'namespace BO2.Services.Generated',
    '{',
    '    internal static class EventMonitorSnapshotContract',
    '    {',
    "        internal const uint SnapshotMagic = $magicLiteral;",
    "        internal const uint SnapshotVersion = $versionLiteral;",
    ('        internal const string SharedMemoryNamePrefix = "{0}";' -f (Get-EscapedCSharpString $sharedMemoryPrefix)),
    ('        internal const string UpdateEventNamePrefix = "{0}";' -f (Get-EscapedCSharpString $updateEventPrefix)),
    ('        internal const string StopEventNamePrefix = "{0}";' -f (Get-EscapedCSharpString $stopEventPrefix)),
    '    }',
    '}'
)

if ($Check) {
    $nativeFresh = Test-GeneratedFile $nativePath $nativeContent
    $managedFresh = Test-GeneratedFile $managedPath $managedContent
    if (-not ($nativeFresh -and $managedFresh)) {
        exit 1
    }

    Write-Host 'Event Monitor Snapshot Contract generated files are up to date.'
    exit 0
}

New-Item -ItemType Directory -Force -Path (Split-Path -Parent $nativePath), (Split-Path -Parent $managedPath) | Out-Null
[System.IO.File]::WriteAllText($nativePath, $nativeContent, $utf8NoBom)
[System.IO.File]::WriteAllText($managedPath, $managedContent, $utf8NoBom)
Write-Host 'Event Monitor Snapshot Contract generated files updated.'
